#!/usr/bin/env python3
import csv, subprocess, datetime, urllib.request, io

SHEET_ID   = "1n35yVc-lpZbmjAdHYbCwmUhrllMfPmlBfy2Hp9uA2Hg"
SHEET_NAME = "HISTORICAL DATA"
FROM_EMAIL = "andy@andyramoselectric.com"
TO_EMAIL   = "andyramos@andyramoselectric.com"
DAYS_AHEAD = 1  # send reminder when due date is within this many days

DATE_FORMATS = ["%B %d %Y", "%m/%d/%Y", "%Y-%m-%d"]

def parse_date(s):
    s = s.strip()
    for fmt in DATE_FORMATS:
        try:
            return datetime.datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None

def send_email(subject, body, to, from_email):
    script = f'''
set emailBody to "{body}"
tell application "Mail"
  set senderAccount to first account whose email addresses contains "{from_email}"
  set newMsg to make new outgoing message with properties {{subject:"{subject}", content:emailBody, sender:"{from_email}", visible:false}}
  tell newMsg
    make new to recipient with properties {{address:"{to}"}}
    set account to senderAccount
  end tell
  send newMsg
end tell
'''
    subprocess.run(["osascript", "-e", script], check=True)

def main():
    url = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:csv&sheet={SHEET_NAME.replace(' ', '%20')}"
    with urllib.request.urlopen(url) as r:
        content = r.read().decode("utf-8")

    today   = datetime.date.today()
    cutoff  = today + datetime.timedelta(days=DAYS_AHEAD)

    reader  = csv.DictReader(io.StringIO(content))
    sent    = 0

    for row in reader:
        status = row.get("STATUS", "").strip().lower()
        if status not in ("open",):
            continue

        raw_date = row.get("Current Date Offers Due", "").strip()
        due = parse_date(raw_date)
        if due is None or due > cutoff or due < today:
            continue

        title      = row.get("TITLE", "").strip()
        facility   = (row.get("Facility") or row.get("Office") or "").strip()
        notice_id  = row.get("Notice ID:", "").strip() or "Not provided in file"
        priority   = row.get("Priority", "").strip() or "Not provided in file"
        city       = row.get("CITY", "").strip()
        state      = row.get("STATE", "").strip()
        notes      = row.get("REASON FOR LOSS", "").strip() or "Not provided in file"
        days_left  = (due - today).days
        urgency    = "TODAY" if days_left == 0 else f"TOMORROW ({due.strftime('%B %d, %Y')})"

        subject = f"[ACTION REQUIRED] {title} – {facility}"

        body = (
            f"This is an automated reminder generated by ARE Bid Tracker 2026.\\n\\n"
            f"The following bid is due {urgency}. Please review and take action.\\n\\n"
            f"BID DETAILS\\n"
            f"----------------------------------------\\n"
            f"Project / Bid Name:    {title}\\n"
            f"Facility / Location:   {facility}\\n"
            f"City / State:          {city}, {state}\\n"
            f"Solicitation Number:   {notice_id}\\n"
            f"Current Status:        {status.capitalize()}\\n"
            f"Priority:              {priority}\\n"
            f"Due Date:              {raw_date}\\n"
            f"Notes / Description:   {notes}\\n"
            f"----------------------------------------\\n\\n"
            f"ACTION REQUIRED:\\n"
            f"Please review this record and update its status if any changes have occurred "
            f"(e.g., submitted, closed, awarded, or withdrawn).\\n\\n"
            f"This reminder was sent automatically by ARE Bid Tracker 2026."
        )

        send_email(subject, body, TO_EMAIL, FROM_EMAIL)
        print(f"Sent: {subject}")
        sent += 1

    print(f"Done. {sent} reminder(s) sent.")

if __name__ == "__main__":
    main()
